name: Build Spring Boot App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'amazon correto'

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      # 빌드 결과물 확인
      - name: List build directory
        run: ls -la build/libs

#      # 아티팩트 저장 경로도 변경
#      - name: Upload build artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: application-jar
#          path: target/*.jar
