name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      # 배포 패키지 준비
      - name: Prepare deployment
        run: |
          mkdir -p deploy
          cp target/*.jar deploy/application.jar
          cp scripts/deploy.sh deploy/
          ls -la deploy

      # SSH로 EC2에 파일 전송
      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.aws_ec2.EC2_HOST }}
          username: ${{ secrets.aws_ec2.EC2_USERNAME }}
          key: ${{ secrets.aws_ec2.EC2_SSH_KEY }}
          source: "deploy/*"
          target: "/home/${{ secrets.aws_ec2.EC2_USERNAME }}"
          strip_components: 1

      # SSH로 EC2에 접속하여 배포 스크립트 실행
      - name: Execute deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.aws_ec2.EC2_HOST }}
          username: ${{ secrets.vEC2_USERNAME }}
          key: ${{ secrets.aws_ec2.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.aws_ec2.EC2_USERNAME }}
            chmod +x deploy.sh
            ./deploy.sh
